# 设置启用环境
spring:
  profiles:
    active: dev
---
spring:
  # 设置开发环境
  config:
    activate:
      on-profile: dev
  # 设置数据源
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mycase_db?useSSL=false&useServerPrepStmts=true
    username: root
    password: mj034416
    type: com.alibaba.druid.pool.DruidDataSource
  # 设置单个上传文件的大小（默认为1MB）
  servlet:
    multipart:
      max-file-size: 5MB
      # 设置一次请求最大上传文件的大小（默认为10MB）
      max-request-size: 100MB
  #设置公开静态目录
#  web:
#    resources:
##      static-locations: classpath:/static/, file:/static/images/
#      static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:D:/java-basic/static/images/
# 开启驼峰命名自动映射
mybatis:
  configuration:
    map-underscore-to-camel-case: true
    # 配置mybatis输出日志
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#开启spring事务管理日志
logging:
  config: classpath:config/logback-spring.xml
  level:
    org.springframework.jdbc.support.JdbcTransactionManager: debug
dir:
  domain: "D:\\\\demo\\\\"
---
spring:
  # 设置开发环境
  config:
    activate:
      on-profile: pro
  # 设置数据源
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://43.136.100.12:3306/zmj?useSSL=false&useServerPrepStmts=true
    username: zmj
    password: zhuangmujie
    type: com.alibaba.druid.pool.DruidDataSource
  # 设置单个上传文件的大小（默认为1MB）
  servlet:
    multipart:
      max-file-size: 5MB
      # 设置一次请求最大上传文件的大小（默认为10MB）
      max-request-size: 100MB
# 开启驼峰命名自动映射
mybatis:
  configuration:
    map-underscore-to-camel-case: true
    # 配置mybatis输出日志
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#开启spring事务管理日志
logging:
  config: classpath:config/logback-spring.xml
  level:
    org.springframework.jdbc.support.JdbcTransactionManager: debug
server:
  port: 8081
